### ISSUE TITLE
Multiple bindings matched from PLC module

### ISSUE THREAD

**Issue by mmierzwa** [thefex/MvvmCross.Adapter.Ninject#1]
H,

I'm developing Xamarin project with MvvmCross with Ninject Adapter. I implemented the `NinjectDependenciesProvider` as suggested in Wiki:

    public class NinjectIosDependenciesProvider : NinjectDependenciesProvider
    {
        protected override IEnumerable<INinjectModule> GetPlatformSpecificModules()
        {
            return new[]
            {
                new IosNinjectModule()
            };
        }

        protected override IEnumerable<INinjectModule> GetPortableNinjectModules()
        {
            return new[]
            {
                new CommonDependenciesModule()
            };
        }
    }

`CommonDependenciesModule` is placed in PCL and `IosNinjectModule` in my iOS project. They are standard Ninject modules:

	internal class IosNinjectModule : NinjectModule
	{
		public override void Load()
		{
			Bind<IActiveDirectoryAuthenticationService>().To<ActiveDirectoryAuthenticationService>();
			Bind<IBlobCache>().ToMethod(ctx => BlobCache.LocalMachine);
			Bind<ISecureBlobCache>().ToMethod(ctx => BlobCache.Secure);
			Bind<IAnalyticsTrackingService>().To<AnalyticsTrackingService>();
		}
	}

    public class CommonDependenciesModule : NinjectModule
    {
        public override void Load()
        {
            Bind<IRoomReservationService>().To<MockedRoomsListReservationService>();
        }
    }

As you can see no bindings are overlapping. 

When MvvmCross is trying to resolve the `IRoomReservationService` type to create a view model I receive the following error:

    Error activating IRoomReservationService
    More than one matching bindings are available.
    Matching bindings:
      1) binding from IRoomReservationService to MockedRoomsListReservationService
      2) binding from IRoomReservationService to method
      3) binding from IRoomReservationService to method
    Activation path:
      2) Injection of dependency IRoomReservationService into parameter roomReservationService of constructor of type RoomsListViewModel
      1) Request for RoomsListViewModel
    Suggestions:
      1) Ensure that you have defined a binding for IRoomReservationService only once.

Two matching bindings to methods are complete mystery for me.  Any clue what might be the cause?

**Comment by thefex** [comment]
I will take a look at that - and ping you back. In case it's bug in Ninject Provider I will push nuget update.

**Comment by mmierzwa** [comment]
Hi,

It looks like it's not a bug but misconfiguration in my code. I copied the auto-registration code for all types named with "Service" postfix (from MvvmCross tutorial) and forgot about it. Since I have two implementations of `IRoomReservationService` in my PCL it ended up with those two mysterious "to method" bindings registered automatically on app startup.
I will confirm this shortly and get back to you.

**Comment by mmierzwa** [comment]
You can close this issue. I confirm that this was due to my misconfiguration.
